### ISSUE TITLE
Add visual studio solution

### ISSUE THREAD

**Issue by mdspielman** [SolaceSamples/solace-samples-dotnet#1]
It would be nice to have a visual studio solution for visual studio users. Using other dotnet repositories for inspiration, a suggested project setup for this would be:

```
-
 |- lib - Readme
 |- docs - As they are now
 |- src - Similar to how it is now. One dir / application
 |- build - All build files
 |- sln file
```

The readme in lib would just be there to explain that you need to copy the Solace API DotNet libs there.

This issue should only be attempted once all the dev portal samples are ported to GitHub

**Comment by tzoght** [comment]
Sounds good Mark, please assign it to me

**Comment by Mrc0113** [comment]
Closing stale issue due to inactivity. 😴
To have this issue re-opened please add a comment below with a detailed explanation.
Thank you for your contributions ❤️
