### ISSUE TITLE
Need instructions for installing the API using nuget.org

### ISSUE THREAD

**Issue by ghost** [SolaceSamples/solace-samples-dotnet#11]
This Solace Messaging API is going to be available through nuget.org, the tutorials need instructions for installing the API from there.

**Comment by mdspielman** [comment]
Sounds excellent. When will they be available?

**Comment by mdspielman** [comment]
It would be good if did the following things while fixing this issue:

1) Update the tutorial instructions following the model seen in Java: https://github.com/SolaceSamples/solace-samples-java/blob/master/docs/_tutorials/publish-subscribe.md#obtaining-the-solace-api
2) Update the readme to simplify the build instructions.
3) Update the project builds use NuGet as the default method of obtaining the Solace client library.

**Comment by dfedorov-solace** [comment]
Mark please take it as it is for now, I really don't have time for a do-over, I'm sorry. Feel free to open an issue for that and I'll fix it when I'm less busy.

The new API is scheduled for this Friday.

**Comment by ghost** [comment]
I'll see what I can do
