### ISSUE TITLE
How do I keep receiving messages?

### ISSUE THREAD

**Issue by RPG345** [SolaceSamples/solace-samples-dotnet#43]
How can I keep my consumer receiving normally ?
If my program terminates for some reasion, how can I restart receiving messages without losing any messages ?
Is there any way I can start getting messages from a few days ago?

**Comment by TamimiGitHub** [comment]
Hey @RPG345 ! This question might be worth asking on our community forum on https://solace.community/ 😄

**Comment by RPG345** [comment]
ok, Thank you~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tamimi Ahmad"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月17日(星期二) 晚上11:10
收件人:&nbsp;"SolaceSamples/solace-samples-dotnet"<solace-samples-dotnet@noreply.github.com&gt;;
抄送:&nbsp;"潇潇暮落雨"<1134495321@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [SolaceSamples/solace-samples-dotnet] How do I keep receiving messages? (#43)





 
Hey @RPG345 ! This question might be worth asking on our community forum on https://solace.community/
