### ISSUE TITLE
How can I connect to the SOLACE via the "smfs://" protocol in dotnet api?

### ISSUE THREAD

**Issue by NCrab1998** [SolaceSamples/solace-samples-dotnet#46]
according to the documentation:
https://docs.solace.com/API-Developer-Online-Ref-Documentation/net/html/3d8e6034-0f60-467b-340b-aa63a4555f3a.htm

it only supports tcp/tcps/http/https protocol, excluding smfs.

**Comment by Mrc0113** [comment]
Hi @NCrab1998, 

If you use tcp/tcps it will actually be using Solace SMF. SMF is over TCP.

**Comment by NCrab1998** [comment]
thx @Mrc0113 ,

I used a url provided by other, 

SessionProperties.Host = "sfms://hostname:55443",
SolClient returned an error message
````````````````````````````````````````````````````````````````````````
``` Operation Error: ReturnCode = SOLCLIENT_FAIL Error Info: (Subcode=UnresolvedHost, Error string=host names in the hostlist ``` 'sfms://hostname:55443' could not be resolved from session '(c0,s1)_vpn-sit-d1' configuration property 'SESSION_HOST', Response code= 0 )
`````````````````````````````````````````````````````````````````````````

I read the document mentioned above, and modify the url to "tcps://hostname:55443"
another error occurred (Subcode=LoginFailure)

It is estimated that the service is already connected.

**Comment by Mrc0113** [comment]
Hi @NCrab1998, 

It looks like (Subcode=LoginFailure) usually means a bad username/password. Are you setting that as well? 

https://docs.solace.com/API-Developer-Online-Ref-Documentation/net/html/1dd5e649-a3ad-e357-604c-c56486a6db94.htm
![image](https://user-images.githubusercontent.com/1815312/126349229-51dc5d21-de9f-45f3-87a9-32aa68d2a019.png)

**Comment by NCrab1998** [comment]
Hi @Mrc0113 ,

"LoginFailure" is another  problem, don't worry about it for now.

I am thinking that since "sfms://" can be write as "tcps://",
can SolClient be handled directly as "tcps://......" when I set host="sfms://......",

can you convey this advice to the developers of "SolaceSystems.Solclient.Messaging" library?
thank you !

**Comment by Mrc0113** [comment]
Hey @NCrab1998, 

Note that you have `sfms` instead of `smfs`. I wouldn't be surprised if it would actually work if spelled right. That said, the options are in our docs here: https://docs.solace.com/API-Developer-Online-Ref-Documentation/net/html/3d8e6034-0f60-467b-340b-aa63a4555f3a.htm

You can use `tcp`, `tcps`, `http`, `https` or no protocol (which defaults to tcp). I'm not sure there is really a good reason to add `smf` and `smfs` as options since it's the same as `tcp` and `tcps`.

**Comment by NCrab1998** [comment]
thx @Mrc0113 

I'm sorry it was misspelled as `sfms `

I have a new problem now. 
The customer asked us to capture and record `JMSMessageID, JMSCorrelationID, JMSTimestamp` (for tracking purpose)
What are their corresponding properties in .netapi ?

![1627433878](https://user-images.githubusercontent.com/23547698/127246542-d55effbb-a8ec-4029-9ee4-98537fbaaae6.png)

**Comment by Mrc0113** [comment]
Hi @NCrab1998, 

You can find a mapping of JMS Header fields to their Solace equivalents here: https://docs.solace.com/Solace-JMS-API/Message-Components.htm

Note that the "Contained in" column is important. You won't be able to see the ones marked as "message property" in PS+ Manager, but you'll still be able to retrieve them via the API. 

For future questions I'd suggest asking over on the [Solace Community forum](https://solace.community/) as more people will see your questions there :)

**Comment by Mrc0113** [comment]
Closing this issue since the issue in the title has been resolved.
