### ISSUE TITLE
Compatibility with AMQP

### ISSUE THREAD

**Issue by SubasishMohapatra** [SolaceSamples/solace-samples-dotnet#48]
Does this .Net SolClient library package work with Solace message broker on AMQP protocol as well?
Last I checked with an url prefixed with amqps it threw an error while parsing the HostUrl.
  SessionProperties sessionProps = new SessionProperties()
            {
                Host = "ws://172.22.0.2:8008", //This works
                **Host = "amqps://172.22.0.2:5672",  //Doesn't work**

**Comment by aaron-613** [comment]
Hi Subasish.  No, these particular .NET samples use the Solace Native API for **SMF** protocol, either over WebSocket or TCP.  For AMQP protocol implementations, I'd suggest looking at maybe https://github.com/Azure/amqpnetlite or http://azure.github.io/amqpnetlite/ ?
