### ISSUE TITLE
Nuget build target to copy native dlls 

### ISSUE THREAD

**Issue by pancake-boy** [SolaceSamples/solace-samples-dotnet#54]
The solace package requires the use of native libs like libsolclient.dll
These are normally copied by using the build targets specified in the SolaceSystems.SolClient.Messaging.targets file.
However, when I use a class library project and set the targetframework to net7.0-windows, it no longer makes use of the correct targets file.

Any idea what I can do?

**Comment by cjwmorgan-sol** [comment]
The SolaceSystems.SolClient.Messaging.targets is only used on the NetFramework (pre 4.6.2) builds. Where the targets file copies either the x86 windows binaries or the x64 windows binaries for a netframework target framework.

.Net or .Netstandard apps do not build the same as netframework as the app can be portable to multiple operation systems not just windows. So the build for .Net apps or class library does not include all dependency binaries in the output folder as a part of build. This does include a generated (app).runtime.json and (app).deps.json for the application or class library. However there is a new post build cycle step call publish for dotnet applications and class libraries. Where the runtime binaries (in this case the native solace binaries) are included in the new sub output folder, default location would be (outputdir)/publish, which would include a new folder struct for multi-platform dotnet lib or app.

See, the microsoft documentation on how to publish applications, https://learn.microsoft.com/en-us/dotnet/core/deploying/.

Where a class library dependent on the Solace nuget package can publish a Class Library using a portable to include a runtimes directory with all supported solace native runtimes and a framework dependent deployment that only include the dependent binaries for a specific target runtime eg. win-x64. That include the built class library the management SolaceSystems.Solclient.Message.dll and the specific native runtime binaries for libsolclient.
